name: build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu:
    strategy:
      matrix:
        include:
          - compiler: gcc
            cxxcompiler: g++
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: install packages and build
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev
        cmake -Bbuild -G "Unix Makefiles"
        cd build
        make
  windows-mingw:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: sdl2
      shell: cmd
      run: curl https://www.libsdl.org/release/SDL2-devel-2.0.14-mingw.tar.gz -L -o sdl2mingw.tar.gz & tar xzvf sdl2mingw.tar.gz & setx -m SDL2DIR "%CD%\SDL2-2.0.14\x86_64-w64-mingw32"
    - name: sdl2-image
      shell: cmd
      run: curl https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-mingw.tar.gz -L -o sdl2imagemingw.tar.gz & tar xzvf sdl2imagemingw.tar.gz & setx -m SDL2IMAGEDIR "%CD%\SDL2_image-2.0.5\x86_64-w64-mingw32"
    - name: sdl2-mixer
      shell: cmd
      run: curl https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-mingw.tar.gz -L -o sdl2mixermingw.tar.gz & tar xzvf sdl2mixermingw.tar.gz & setx -m SDL2MIXERDIR "%CD%\SDL2_mixer-2.0.4\x86_64-w64-mingw32"
    - name: sdl2-ttf
      shell: cmd
      run: curl https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-mingw.tar.gz -L -o sdl2ttfmingw.tar.gz & tar xzvf sdl2ttfmingw.tar.gz & setx -m SDL2TTFDIR "%CD%\SDL2_ttf-2.0.15\x86_64-w64-mingw32"
    - name: build
      shell: cmd
      run: refreshenv & cmake -Bbuild -G "MinGW Makefiles" & cd build & mingw32-make.exe

  windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64_x86
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: sdl2
        shell: cmd
        run: curl https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip -L -o sdl2vc.zip & tar xf sdl2vc.zip & setx -m SDL2DIR "%CD%\SDL2-2.0.14"
      - name: sdl2-image
        shell: cmd
        run: curl https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip -L -o sdl2imagevc.zip & tar xf sdl2imagevc.zip & setx -m SDL2IMAGEDIR "%CD%\SDL2_image-2.0.5"
      - name: sdl2-mixer
        shell: cmd
        run: curl https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip -L -o sdl2mixervc.zip & tar xf sdl2mixervc.zip & setx -m SDL2MIXERDIR "%CD%\SDL2_mixer-2.0.4"
      - name: sdl2-ttf
        shell: cmd
        run: curl https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip -L -o sdl2ttfvc.zip & tar xf sdl2ttfvc.zip & setx -m SDL2TTFDIR "%CD%\SDL2_ttf-2.0.15"
      - name: Build
        run: |
          $env:SDL2DIR = [System.Environment]::GetEnvironmentVariable("SDL2DIR","Machine")
          $env:SDL2IMAGEDIR = [System.Environment]::GetEnvironmentVariable("SDL2IMAGEDIR","Machine")
          $env:SDL2MIXERDIR = [System.Environment]::GetEnvironmentVariable("SDL2MIXERDIR","Machine")
          $env:SDL2TTFDIR = [System.Environment]::GetEnvironmentVariable("SDL2TTFDIR","Machine")
          cmake -Bbuild -G "NMake Makefiles"
          cd build
          nmake
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: install packages and build
      shell: bash
      run: |
        brew install sdl2
        brew install sdl2_image
        brew install sdl2_mixer
        brew install sdl2_ttf
        cmake -Bbuild -G "Unix Makefiles"
        cd build
        make